name: docker

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get tags
        id: get_tags
        run: |
            TAG=${GITHUB_REF/refs\/tags\/v/}
            echo ::set-output name=VERSION::$TAG
            echo ::set-output name=TAG1::${{ secrets.DOCKERHUB_USERNAME }}/vipien:latest
            echo ::set-output name=TAG2::${{ secrets.DOCKERHUB_USERNAME }}/vipien:$TAG

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm
          push: true
          build-args: |
            VERSION=${{ steps.get_tags.outputs.VERSION }}
          tags: |
            ${{ steps.get_tags.outputs.TAG1 }}
            ${{ steps.get_tags.outputs.TAG2 }}